from datetime import date
from typing import List, Dict, Any
from modules.career.models import JobAnalysis, TrendAnalysis, SkillGapAnalysis


class CareerPresenter:
    """
    분석 결과를 Slack Block Kit으로 변환한다.
    LLM 없이 코드 기반으로 조립해 hallucination을 방지한다.
    """

    @staticmethod
    def build_daily_report(
        report_date: date,
        job_analysis: JobAnalysis,
        trend_analysis: TrendAnalysis,
        skill_gap: SkillGapAnalysis,
        job_count_wanted: int,
        job_count_jumpit: int,
    ) -> Dict[str, Any]:
        blocks: List[Dict[str, Any]] = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"🚀 커리어 Daily Report — {report_date}",
                    "emoji": True,
                },
            },
            {"type": "divider"},
        ]

        # ── 채용공고 섹션 ──────────────────────────────────────────────
        top_skills_str = ", ".join(job_analysis.top_skills[:6]) if job_analysis.top_skills else "데이터 없음"
        salary = job_analysis.salary_range
        salary_str = ""
        if salary.get("median"):
            m = salary["median"] // 10000 if salary["median"] > 10000 else salary["median"]
            salary_str = f"\n💰 연봉 중앙값 *{m}만원*"

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*💼 채용공고 요약* — Wanted {job_count_wanted}건 + 점핏 {job_count_jumpit}건\n"
                    f"🔑 핵심 스킬: {top_skills_str}"
                    f"{salary_str}\n"
                    f"📊 {job_analysis.hiring_signal}"
                ),
            },
        })

        if job_analysis.notable_postings:
            notable_text = "\n".join(
                f"• <{p.get('url')}|{p.get('company')} — {p.get('position')}>"
                for p in job_analysis.notable_postings[:3]
            )
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*주목할 포지션:*\n{notable_text}"},
            })

        blocks.append({"type": "divider"})

        # ── 기술 트렌드 섹션 ──────────────────────────────────────────
        hot_topics_str = ", ".join(trend_analysis.hot_topics[:5]) if trend_analysis.hot_topics else ""
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*🔥 기술 트렌드*\n"
                    f"🌟 핫 토픽: {hot_topics_str}\n"
                    f"📰 HN: {trend_analysis.hn_highlight}\n"
                    f"💡 {trend_analysis.backend_relevance_comment}"
                ),
            },
        })

        if trend_analysis.github_top:
            github_text = "\n".join(
                f"• <{r.get('url')}|{r.get('name')}> ({r.get('language')}) ⭐{r.get('stars_today')}"
                for r in trend_analysis.github_top[:3]
            )
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*GitHub 주목 레포:*\n{github_text}"},
            })

        blocks.append({"type": "divider"})

        # ── 스킬 갭 섹션 ──────────────────────────────────────────────
        gap_score = skill_gap.gap_score
        gap_bar = _score_bar(gap_score)
        missing_str = ", ".join(
            f"{s.get('skill')}({s.get('urgency', '').upper()[0]})"
            for s in skill_gap.missing_skills[:5]
        ) if skill_gap.missing_skills else "없음"

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*🎯 스킬 갭 분석*\n"
                    f"갭 점수: *{gap_score}/100* {gap_bar}"
                    + (f" ({skill_gap.gap_trend})" if skill_gap.gap_trend else "")
                    + f"\n부족 스킬: {missing_str}"
                ),
            },
        })

        if skill_gap.study_recommendations:
            rec_text = "\n".join(
                f"{i}. *{r.get('topic')}* — {r.get('why', '')}"
                for i, r in enumerate(skill_gap.study_recommendations[:3], 1)
            )
            blocks.append({
                "type": "section",
                "text": {"type": "mrkdwn", "text": f"*오늘의 학습 추천:*\n{rec_text}"},
            })

        blocks.append({
            "type": "context",
            "elements": [
                {"type": "mrkdwn", "text": f"Generated by Consigliere · {report_date}"}
            ],
        })

        return {"blocks": blocks}


def _score_bar(score: int) -> str:
    filled = score // 10
    return "🟥" * filled + "⬜" * (10 - filled)
